### ISSUE TITLE
csv2-main crashed

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#131]
csv2-min crashed with following traceback:
```
Dec 17 03:14:37 csv2 csv2: 2018-12-17 03:14:37,182 - MainProcess      - DEBUG - Done checking atlas unregistered VMs.
Dec 17 03:14:37 csv2 csv2: 2018-12-17 03:14:37,191 - MainProcess      - DEBUG - Done counting current flavors for group: atlas.
Dec 17 03:14:37 csv2 csv2: 2018-12-17 03:14:37,192 - MainProcess      - DEBUG - Group: atlas Current flavors: defaultdict(<function count_cloud_flavors.<locals>.<lambda> at 0x7f5e47d550d0>, {})
Dec 17 03:14:37 csv2 csv2: 2018-12-17 03:14:37,194 - MainProcess      - DEBUG - ---------------got idle jobs--------------
Dec 17 03:14:37 csv2 csv2: 2018-12-17 03:14:37,214 - MainProcess      - DEBUG - Dealing with current group: belle
Dec 17 03:14:37 csv2 csv2: 2018-12-17 03:14:37,567 - MainProcess      - DEBUG - Added all clouds for group: belle
Dec 17 03:14:37 csv2 csv2: 2018-12-17 03:14:37,568 - MainProcess      - DEBUG - Check Idle Machines for Keep Alive time for: belle
Dec 17 03:15:07 csv2 csv2: Traceback (most recent call last):
Dec 17 03:15:07 csv2 csv2: File "/opt/cloudscheduler/csmain", line 517, in <module>
Dec 17 03:15:07 csv2 csv2: main()
Dec 17 03:15:07 csv2 csv2: File "/opt/cloudscheduler/csmain", line 86, in main
Dec 17 03:15:07 csv2 csv2: check_idle_time(csgroup.group_name, config)
Dec 17 03:15:07 csv2 csv2: File "/opt/cloudscheduler/csmain", line 371, in check_idle_time
Dec 17 03:15:07 csv2 csv2: config.db_open()
Dec 17 03:15:07 csv2 csv2: File "/opt/cloudscheduler/lib/db_config.py", line 127, in db_open
Dec 17 03:15:07 csv2 csv2: self.db_connection = self.db_engine.connect()
Dec 17 03:15:07 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
Dec 17 03:15:07 csv2 csv2: return self._connection_cls(self, **kwargs)
Dec 17 03:15:07 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
Dec 17 03:15:07 csv2 csv2: if connection is not None else engine.raw_connection()
Dec 17 03:15:07 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
Dec 17 03:15:07 csv2 csv2: self.pool.unique_connection, _connection)
Dec 17 03:15:07 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
Dec 17 03:15:07 csv2 csv2: return fn()
Dec 17 03:15:07 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 342, in unique_connection
Dec 17 03:15:07 csv2 csv2: return _ConnectionFairy._checkout(self)
Dec 17 03:15:07 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 788, in _checkout
Dec 17 03:15:07 csv2 csv2: fairy = _ConnectionRecord.checkout(pool)
Dec 17 03:15:07 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 529, in checkout
Dec 17 03:15:07 csv2 csv2: rec = pool._do_get()
Dec 17 03:15:07 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 1186, in _do_get
Dec 17 03:15:07 csv2 csv2: (self.size(), self.overflow(), self._timeout), code="3o7r")
Dec 17 03:15:07 csv2 csv2: sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30 (Background on this error at: http://sqlalche.me/e/3o7r)
```

**Comment by mhpx** [comment]
I've added try/except blocks around more of the db related code to try and deal with this issue. It may be worth looking at the connection limit on the db itself.

https://github.com/hep-gc/cloudscheduler/commit/4cad52a6f23df470e19ce952849f1b86aa9a9667
