### ISSUE TITLE
csv2-main crashes repeatedly in DB related code

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#136]
at least the last 3 crashes of csv2-main are for the same reason:
```
Dec 24 00:53:11 csv2 csv2: 2018-12-24 00:53:11,414 - MainProcess      - DEBUG - Using a v2 session for cc-west-a
Dec 24 00:53:11 csv2 csv2: 2018-12-24 00:53:11,414 - MainProcess      - DEBUG - Added all clouds for group: atlas
Dec 24 00:53:11 csv2 csv2: 2018-12-24 00:53:11,415 - MainProcess      - DEBUG - Check Idle Machines for Keep Alive time for: atlas
Dec 24 00:53:41 csv2 csv2: Traceback (most recent call last):
Dec 24 00:53:41 csv2 csv2: File "/opt/cloudscheduler/csmain", line 517, in <module>
Dec 24 00:53:41 csv2 csv2: main()
Dec 24 00:53:41 csv2 csv2: File "/opt/cloudscheduler/csmain", line 86, in main
Dec 24 00:53:41 csv2 csv2: check_idle_time(csgroup.group_name, config)
Dec 24 00:53:41 csv2 csv2: File "/opt/cloudscheduler/csmain", line 371, in check_idle_time
Dec 24 00:53:41 csv2 csv2: config.db_open()
Dec 24 00:53:41 csv2 csv2: File "/opt/cloudscheduler/lib/db_config.py", line 128, in db_open
Dec 24 00:53:41 csv2 csv2: self.db_connection = self.db_engine.connect()
Dec 24 00:53:41 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2102, in connect
Dec 24 00:53:41 csv2 csv2: return self._connection_cls(self, **kwargs)
Dec 24 00:53:41 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 90, in __init__
Dec 24 00:53:41 csv2 csv2: if connection is not None else engine.raw_connection()
Dec 24 00:53:41 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2188, in raw_connection
Dec 24 00:53:41 csv2 csv2: self.pool.unique_connection, _connection)
Dec 24 00:53:41 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
Dec 24 00:53:41 csv2 csv2: return fn()
Dec 24 00:53:41 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 342, in unique_connection
Dec 24 00:53:41 csv2 csv2: return _ConnectionFairy._checkout(self)
Dec 24 00:53:41 csv2 csv2: File "/usr/lib64/python3.6/site-packages/sqlalchemy/pool.py", line 788, in _checkout
Dec 24 00:53:41 csv2 csv2: fairy = _ConnectionRecord.checkout(pool)
```

**Comment by mhpx** [comment]
@crlb this happens when doing the db_open and it runs out of connections in the default queuepool. Do we want to look at putting in some kind of retry or handling of the problem within db_config.py?
