### ISSUE TITLE
no /etc/ssl/certs/CABundle.crt on csv2-dev2

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#143]
strangely enough, it didn't stop csv2 from booting VMs earlier in the group "testing",
This problem should now be created from the second grouptest-dev2.

I will copy over the file from the csv2 machine, but installation should be part of ansible and updated regularly.

```
2019-01-31 15:32:47,994 - csmain       - DEBUG - Making authentication request to https://nova-ab.dair-atir.canarie.ca:5000/v2.0/tokens
2019-01-31 15:32:47,997 - csmain       - ERROR - Disable cloud dair-qc due to exception(later).
Traceback (most recent call last):
  File "/opt/cloudscheduler/cloudscheduler/csmain", line 257, in main
    image = use_image)
  File "/opt/cloudscheduler/cloudscheduler/openstackcloud.py", line 110, in vm_create
    imageobj = nova.glance.find_image(self.default_image)
  File "/usr/lib/python3.6/site-packages/novaclient/v2/images.py", line 53, in find_image
    "images")
  File "/usr/lib/python3.6/site-packages/novaclient/base.py", line 257, in _list
    resp, body = self.api.client.get(url)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 351, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/lib/python3.6/site-packages/novaclient/client.py", line 77, in request
    **kwargs)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 510, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 213, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/session.py", line 684, in request
    auth_headers = self.get_auth_headers(auth)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/session.py", line 1071, in get_auth_headers
    return auth.get_headers(self, **kwargs)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/plugin.py", line 95, in get_headers
    token = self.get_token(session)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/identity/base.py", line 88, in get_token
    return self.get_access(session).auth_token
  File "/usr/lib/python3.6/site-packages/keystoneauth1/identity/base.py", line 134, in get_access
    self.auth_ref = self.get_auth_ref(session)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/identity/v2.py", line 63, in get_auth_ref
    authenticated=False, log=False)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/session.py", line 1019, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/session.py", line 814, in request
    resp = send(**kwargs)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/session.py", line 903, in _send_request
    resp = self.session.request(method, url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 416, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 228, in cert_verify
    "invalid path: {}".format(cert_loc))
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /etc/ssl/certs/CABundle.crt
```

**Comment by rseuster** [comment]
ln -s /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem /etc/ssl/certs/CABundle.crt

**Comment by kcasteels** [comment]
The should exist, but it needs to be linked. Do this through Ansible.

**Comment by kcasteels** [comment]
Ansible was able to build successfully with this link. Closing.
