### ISSUE TITLE
ProcessMonitor

### ISSUE THREAD

**Issue by mhpx** [hep-gc/cloudscheduler#146]
got the following while testing some stuff with ProcMon

Traceback (most recent call last):
  File "/home/mhp/cloudscheduler/cloudscheduler/cloudscheduler/lib/ProcessMonitor.py", line 77, in join_all
    proc.join()
TypeError: join() takes exactly one argument (0 given)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./cloudscheduler/csmain", line 518, in <module>
    procMon.join_all()
  File "/home/mhp/cloudscheduler/cloudscheduler/cloudscheduler/lib/ProcessMonitor.py", line 79, in join_all
    logging.error("failed to join process %s", proc.name)
AttributeError: 'str' object has no attribute 'name'

**Comment by mhpx** [comment]
line numbers may be a little off from what's in the actual dev branch.

**Comment by colsond** [comment]
This was a screw up with accessing the process object in the dictionary. It should be fixed with that commit but let me know if you have any more issues.
