### ISSUE TITLE
csv2 webpage - units missing for RAM and print warnings

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#20]
RAM entry under clouds needs an unit

print warning, logfiles are now clogged with warnings like
```
May  3 11:34:41 csv2 csv2: 2018-05-03 11:34:41,370:DEBUG:urllib3.connectionpool:Resetting dropped connection: openstack.tacc.chameleoncloud.org
May  3 11:34:41 csv2 csv2: /usr/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate ve
rification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
May  3 11:34:41 csv2 csv2: InsecureRequestWarning)
May  3 11:34:41 csv2 csv2: 2018-05-03 11:34:41,677:DEBUG:urllib3.connectionpool:https://openstack.tacc.chameleoncloud.org:8774 "GET /v2/FG-54/flavors/3 HTTP/1.1" 200 414
May  3 11:34:41 csv2 csv2: 2018-05-03 11:34:41,678:DEBUG:novaclient.v2.client:RESP: [200] Date: Thu, 03 May 2018 18:34:41 GMT Server: Apache/2.4.6 (CentOS) Content-Type: application/json Content-Length: 414 X-Compute-Request-Id: req-c095ec04-b820-4497-abf7-f6e8a1b165ad Via: 1.1 openstack.tacc.chameleoncloud.org:8774 Connection: close
May  3 11:34:41 csv2 csv2: RESP BODY: {"flavor": {"name": "m1.medium", "links": [{"href": "http://openstack.tacc.chameleoncloud.org:8774/v2/FG-54/flavors/3", "rel": "self"}, {"href": "http://openstack.tacc.chameleoncloud.org:8774/FG-54/flavors/3", "rel": "bookmark"}], "ram": 4096, "OS-FLV-DISABLED:disabled": false, "vcpus": 2, "swap": "", "os-flavor-access:is_public": true, "rxtx_factor": 1.0, "OS-FLV-EXT-DATA:ephemeral": 0, "disk": 40, "id": "3"}}
May  3 11:34:41 csv2 csv2: 2018-05-03 11:34:41,678:DEBUG:novaclient.v2.client:GET call to compute for https://openstack.tacc.chameleoncloud.org:8774/v2/FG-54/flavors/3 used request id req-c095ec04-b820-4497-abf7-f6e8a1b165ad
May  3 11:34:41 csv2 csv2: 2018-05-03 11:34:41,681:DEBUG:novaclient.v2.client:REQ: curl -g -i --cacert "" -X GET https://openstack.tacc.chameleoncloud.org:9696/v2.0/networks?name=private -H "Accept: application/json" -H "X-Auth-Token: {SHA1}14a084abfba60fc21dd91ba2e4b2e8304dd75e68" -H "User-Agent: python-novaclient"
May  3 11:34:41 csv2 csv2: 2018-05-03 11:34:41,682:DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): openstack.tacc.chameleoncloud.org
May  3 11:34:42 csv2 csv2: /usr/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
May  3 11:34:42 csv2 csv2: InsecureRequestWarning)
May  3 11:34:42 csv2 csv2: 2018-05-03 11:34:42,137:DEBUG:urllib3.connectionpool:https://openstack.tacc.chameleoncloud.org:9696 "GET /v2.0/networks?name=private HTTP/1.1" 200 16
May  3 11:34:42 csv2 csv2: 2018-05-03 11:34:42,138:DEBUG:novaclient.v2.client:RESP: [200] Date: Thu, 03 May 2018 18:34:42 GMT Server: Apache/2.4.6 (CentOS) Content-Type: application/json; charset=UTF-8 Content-Length: 16 X-Openstack-Request-Id: req-59275559-c8a9-43a0-b23d-08d5431a7879 Via: 1.1 openstack.tacc.chameleoncloud.org:9696 Connection: close
May  3 11:34:42 csv2 csv2: RESP BODY: {"networks": []}
May  3 11:34:42 csv2 csv2: 2018-05-03 11:34:42,138:DEBUG:novaclient.v2.client:GET call to network for https://openstack.tacc.chameleoncloud.org:9696/v2.0/networks?name=private used request id req-59275559-c8a9-43a0-b23d-08d5431a7879
May  3 11:34:42 csv2 csv2: 2018-05-03 11:34:42,139:ERROR:cloudscheduler.openstackcloud:Unable to list networks for chameleon-rolf-test: Exception: No Network matching private. (HTTP 404)
May  3 11:34:42 csv2 csv2: Traceback (most recent call last):
May  3 11:34:42 csv2 csv2: File "/opt/cloudscheduler/cloudscheduler/openstackcloud.py", line 287, in _find_network
May  3 11:34:42 csv2 csv2: network = nova.neutron.find_network(netname)
May  3 11:34:42 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/v2/networks.py", line 56, in find_network
May  3 11:34:42 csv2 csv2: raise exceptions.NotFound(404, msg)
May  3 11:34:42 csv2 csv2: novaclient.exceptions.NotFound: No Network matching private. (HTTP 404)
May  3 11:34:42 csv2 csv2: 2018-05-03 11:34:42,140:DEBUG:novaclient.v2.client:REQ: curl -g -i --cacert "" -X POST https://openstack.tacc.chameleoncloud.org:8774/v2/FG-54/servers -H "Accept: application/json" -H "X-Auth-Token: {SHA1}14a084abfba60fc21dd91ba2e4b2e8304dd75e68" -H "User-Agent: python-novaclient" -H "Content-Type: application/json" -d '{"server": {"name": "testing-chameleon-rolf-test-140883470876221", "imageRef": "1a56bfcd-2c5e-4348-a406-2ec9b7d58ebb", "flavorRef": "3", "min_count": 1, "max_count": 2}}'
May  3 11:34:42 csv2 csv2: 2018-05-03 11:34:42,141:DEBUG:urllib3.connectionpool:Resetting dropped connection: openstack.tacc.chameleoncloud.org
May  3 11:34:43 csv2 csv2: /usr/lib/python3.6/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
May  3 11:34:43 csv2 csv2: InsecureRequestWarning)
May  3 11:34:43 csv2 csv2: 2018-05-03 11:34:43,097:DEBUG:urllib3.connectionpool:https://openstack.tacc.chameleoncloud.org:8774 "POST /v2/FG-54/servers HTTP/1.1" 403 75
May  3 11:34:43 csv2 csv2: 2018-05-03 11:34:43,098:DEBUG:novaclient.v2.client:RESP: [403] Date: Thu, 03 May 2018 18:34:43 GMT Server: Apache/2.4.6 (CentOS) Retry-After: 0 Content-Length: 75 Content-Type: application/json; charset=UTF-8 X-Compute-Request-Id: req-5abbe12b-9796-4ac4-b8ca-76ca743c692a Via: 1.1 openstack.tacc.chameleoncloud.org:8774 Connection: close
May  3 11:34:43 csv2 csv2: RESP BODY: {"forbidden": {"message": "Maximum number of ports exceeded", "code": 403}}
May  3 11:34:43 csv2 csv2: 2018-05-03 11:34:43,098:DEBUG:novaclient.v2.client:POST call to compute for https://openstack.tacc.chameleoncloud.org:8774/v2/FG-54/servers used request id req-5abbe12b-9796-4ac4-b8ca-76ca743c692a
May  3 11:34:43 csv2 csv2: 2018-05-03 11:34:43,098:ERROR:cloudscheduler.openstackcloud:Maximum number of ports exceeded (HTTP 403) (Request-ID: req-5abbe12b-9796-4ac4-b8ca-76ca743c692a)
May  3 11:34:43 csv2 csv2: Traceback (most recent call last):
May  3 11:34:43 csv2 csv2: File "/opt/cloudscheduler/cloudscheduler/openstackcloud.py", line 167, in vm_create
May  3 11:34:43 csv2 csv2: security_groups=None, max_count=num)
May  3 11:34:43 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 1403, in create
May  3 11:34:43 csv2 csv2: **boot_kwargs)
May  3 11:34:43 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 802, in _boot
May  3 11:34:43 csv2 csv2: return_raw=return_raw, **kwargs)
May  3 11:34:43 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/base.py", line 361, in _create
May  3 11:34:43 csv2 csv2: resp, body = self.api.client.post(url, body=body)
May  3 11:34:43 csv2 csv2: File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 310, in post
May  3 11:34:43 csv2 csv2: return self.request(url, 'POST', **kwargs)
May  3 11:34:43 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/client.py", line 83, in request
May  3 11:34:43 csv2 csv2: raise exceptions.from_response(resp, body, url, method)
```

but clouds entry for this cloud shows no indication.

**Comment by colsond** [comment]
not closing ! updates ?

**Comment by rseuster** [comment]
this issue is solved
