### ISSUE TITLE
cli does not support cloud-name for job list (stable-2.5 cli)

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#229]
```
mebert@heplw65:~/scripts$ cloudscheduler job list -h
Usage: cloudscheduler job list [<options>]
Help requested for "cloudscheduler job list". The following optional parameters may be specified:
  -cn  |  --cloud-name
  -CSV |  --comma-separated-values
  -CSEP |  --comma-separated-values-separator
  -g   |  --group
  -H   |  --long-help
  -h   |  --help
  -jh  |  --job-hold
  -jI  |  --job-id
  -ji  |  --job-image
  -jp  |  --job-priority
  -jR  |  --job-requirements
  -jrc |  --job-request-cpus
  -jrd |  --job-request-disk
  -jrr |  --job-request-ram
  -jrs |  --job-request-swap
  -jS  |  --job-status
  -jtc |  --job-target-clouds
  -ju  |  --job-user
  -NV  |  --no-view
  -ok  |  --only-keys
  -r   |  --rotate
  -s   |  --server
  -V   |  --view
  -VC  |  --view-columns
  -xA  |  --expose-API
For more information, use -H.
mebert@heplw65:~/scripts$ cloudscheduler job list -cn arbutus
Traceback (most recent call last):
  File "/hepuser/mebert/opt/bin/cloudscheduler", line 498, in <module>
    main(sys.argv)
  File "/hepuser/mebert/opt/bin/cloudscheduler", line 420, in main
    gvar['actions'][gvar['object']][1][gvar['action']](gvar)
  File "/hepuser/mebert/opt/bin/csv2_job.py", line 74, in list
    job_list = _filter(gvar, response['job_list'])
  File "/hepuser/mebert/opt/bin/csv2_job.py", line 19, in _filter
    if 'cloud-name' in gvar['command_args'] and qs[_ix]['cloud_name'] != gvar['command_args']['cloud-name']:
KeyError: 'cloud_name'
```

**Comment by crlb** [comment]
Should it? 
The parameter is an artifact of the fact that the code was copied from VM list and should probably have been deleted. 
There is no cloud information for jobs in the database and the value would have to be extracted and maintained from the presence or absence of RemoteHost classad.
Does this really add any value or should we just clean up the job list code?

**Comment by MarcusEbert** [comment]
Well, in the current version it was confusing to have it in the help as an option but it didn't work. 

The reason I found it was because I wanted to list all jobs running on a specific cloud for a specific project to see what kind of jobs run there. How do we list currently the job slots used for each cloud, if it's single or multi core jobs, and how many are on each cloud busy/idle?

**Comment by crlb** [comment]
cloud_name parameter removed, b71dec5d052edd7eaa1e76870cc600ff41f303d9

**Comment by MarcusEbert** [comment]
consistent now
