### ISSUE TITLE
TO BE REVISITED: Stack Traceback during booting of VM on Otter with multiple networks ERROR

### ISSUE THREAD

**Issue by mfens98** [hep-gc/cloudscheduler#245]
We tried to boot a VM on otter where csv2 found multiple networks and didn't boot a VM, instead this traceback was produced. Can we catch this exception?
```
2019-09-19 09:15:16,033 - csmain       - DEBUG - RESP BODY: {"conflictingRequest": {"message": "Multiple possible networks found, use a Network ID to be more specific.", "code": 409}}
2019-09-19 09:15:16,033 - csmain       - DEBUG - POST call to compute for https://otter.heprc.uvic.ca:18774/v2.1/servers used request id req-1d846b21-845c-44dc-9787-c1a61b93fe52
2019-09-19 09:15:16,033 - csmain       - ERROR - Multiple possible networks found, use a Network ID to be more specific. (HTTP 409) (Request-ID: req-1d846b21-845c-44dc-9787-c1a61b93fe52)
Traceback (most recent call last):
  File "/opt/cloudscheduler/cloudscheduler/openstackcloud.py", line 172, in vm_create
    security_groups=self.default_security_groups, max_count=num)
  File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 1481, in create
    return self._boot(response_key, *boot_args, **boot_kwargs)
  File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 846, in _boot
    return_raw=return_raw, **kwargs)
  File "/usr/lib/python3.6/site-packages/novaclient/base.py", line 364, in _create
    resp, body = self.api.client.post(url, body=body)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 392, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python3.6/site-packages/novaclient/client.py", line 78, in request
    raise exceptions.from_response(resp, body, url, method)
novaclient.exceptions.Conflict: Multiple possible networks found, use a Network ID to be more specific. (HTTP 409) (Request-ID: req-1d846b21-845c-44dc-9787-c1a61b93fe52)
2019-09-19 09:15:16,034 - csmain       - ERROR - Disable cloud otter due to exception(later).
Traceback (most recent call last):
  File "/opt/cloudscheduler/cloudscheduler/openstackcloud.py", line 172, in vm_create
    security_groups=self.default_security_groups, max_count=num)
  File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 1481, in create
    return self._boot(response_key, *boot_args, **boot_kwargs)
  File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 846, in _boot
    return_raw=return_raw, **kwargs)
  File "/usr/lib/python3.6/site-packages/novaclient/base.py", line 364, in _create
    resp, body = self.api.client.post(url, body=body)
  File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 392, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/lib/python3.6/site-packages/novaclient/client.py", line 78, in request
    raise exceptions.from_response(resp, body, url, method)
novaclient.exceptions.Conflict: Multiple possible networks found, use a Network ID to be more specific. (HTTP 409) (Request-ID: req-1d846b21-845c-44dc-9787-c1a61b93fe52)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/cloudscheduler/cloudscheduler/csmain", line 389, in main
    image=use_image)
  File "/opt/cloudscheduler/cloudscheduler/openstackcloud.py", line 178, in vm_create
    raise Exception
Exception
2019-09-19 09:15:16,035 - csmain       - DEBUG - Hit the end of clouds_matching_new, anything boot or nothing?
```

**Comment by colsond** [comment]
For now I have added exception handling for this specific trace stack on stable-2.6. The control flow hasn't changed and main still wont be able to boot vms if no network is defined on a cloud with multiple networks. In future versions we should add some reporting or handling for this type of error.

We can:
A) Hold the jobs that don't have proper configuration defined and are not covered by the defaults,
B) Notify the user in some way when a cloud has no defaults defined which could potentially lead to this problem
C) Take action on a cloud that is unable to boot vms due to this reason by either disabling the cloud or notifying users of the issue.

**Comment by MarcusEbert** [comment]
This is a cloud problem, not a group or job problem.
I think we should not hold jobs since jobs should not know anything about the underlying clouds and could also still run on other clouds. Users (==job submitters) should also not be notified for the same reason.

Since that is only cloud specific, I think the best would be to disable the cloud until a network is specified, and display the reason somewhere (in cli and web interface).

**Comment by rseuster** [comment]
Jobs can define a network. Things are muddy. There's currently no easy and straightforward solution. This needs to be reviewed at some point.

**Comment by rseuster** [comment]
should be revisited sometimes soon

**Comment by rseuster** [comment]
close
