### ISSUE TITLE
python stacktrace when no resources available

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#27]
```May 15 09:17:30 csv2 csv2: 2018-05-15 09:17:30,815:DEBUG:urllib3.connectionpool:https://west.cloud.computecanada.ca:8774 "POST /v2/92f1b05c7cb74c288269e47a52ffae3a/servers HTTP/1.1" 403 125
May 15 09:17:30 csv2 csv2: 2018-05-15 09:17:30,816:DEBUG:novaclient.v2.client:RESP: [403] Retry-After: 0 Content-Length: 125 Content-Type: application/json; charset=UTF-8 Date: Tue, 15 May 2018 16:17:30 GMT Connection: keep-alive
May 15 09:17:30 csv2 csv2: RESP BODY: {"forbidden": {"message": "Quota exceeded for instances: Requested 1-2, but already used 700 of 700 instances", "code": 403}}
May 15 09:17:30 csv2 csv2: 2018-05-15 09:17:30,816:ERROR:cloudscheduler.openstackcloud:Quota exceeded for instances: Requested 1-2, but already used 700 of 700 instances (HTTP 403)
May 15 09:17:30 csv2 csv2: Traceback (most recent call last):
May 15 09:17:30 csv2 csv2: File "/opt/cloudscheduler/cloudscheduler/openstackcloud.py", line 167, in vm_create
May 15 09:17:30 csv2 csv2: security_groups=None, max_count=num)
May 15 09:17:30 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 1403, in create
May 15 09:17:30 csv2 csv2: **boot_kwargs)
May 15 09:17:30 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 802, in _boot
May 15 09:17:30 csv2 csv2: return_raw=return_raw, **kwargs)
May 15 09:17:30 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/base.py", line 361, in _create
May 15 09:17:30 csv2 csv2: resp, body = self.api.client.post(url, body=body)
May 15 09:17:30 csv2 csv2: File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 310, in post
May 15 09:17:30 csv2 csv2: return self.request(url, 'POST', **kwargs)
May 15 09:17:30 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/client.py", line 83, in request
May 15 09:17:30 csv2 csv2: raise exceptions.from_response(resp, body, url, method)
May 15 09:17:30 csv2 csv2: novaclient.exceptions.Forbidden: Quota exceeded for instances: Requested 1-2, but already used 700 of 700 instances (HTTP 403)
May 15 09:17:30 csv2 csv2: 2018-05-15 09:17:30,817:DEBUG:cloudscheduler.openstackcloud:vm create
```

**Comment by rseuster** [comment]
even worse, the dashboard tells me we have only 548 VMs running, far from the 700 claimed in the output

**Comment by mhpx** [comment]
Right now the code is catching the exception but not doing anything in particular to handle it. 

The dashboard difference was due to me cleaning up the extra VMs at that time.
