### ISSUE TITLE
problem uploading group yaml file

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#37]
```
[seuster@csv2 ~]$ cloudscheduler group yaml-load -f ~/certs.yaml -yn certs
Traceback (most recent call last):
  File "/usr/local/bin/cloudscheduler", line 304, in <module>
    main(sys.argv)
  File "/usr/local/bin/cloudscheduler", line 235, in main
    gvar['actions'][gvar['object']][1][gvar['action']](gvar)
  File "/opt/cloudscheduler/cli/bin/csv2_group.py", line 364, in yaml_load
    **verify_yaml_file(gvar['user_settings']['file-path']),
  File "/opt/cloudscheduler/cli/bin/csv2_common.py", line 384, in verify_yaml_file
    result = _yaml_load_and_verify(yaml)
NameError: name 'yaml' is not defined
```
~/certs.yaml does exist

**Comment by rseuster** [comment]
after some updates, still no success. Now
```
$ cloudscheduler group yaml-load -f ~/certs.yaml -yn certs  -ymt cloud-config
Error: GV28-558 group yaml-add "atlas::certs" failed - (1364, "Field 'mime_type' doesn't have a default value").
```
