### ISSUE TITLE
cloudscheduler doesn't forget VM instances removed externally 

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#40]
Yesterday I deleted VMs on cc-west-a on the openstack dashboard. This morning csv2 still remembers them, and doesn't start new VMs because of that.

**Comment by colsond** [comment]
It seems there was an error in the openstack poller and the thread died. Some sqlalchemy error by the looks of the system log.
metadata log:
```
2018-05-31 17:18:17,372 - VM Poller    - INFO - Polling VMs from group:cloud -  atlas:cc-west-a
2018-05-31 17:18:28,323 - MainProcess  - ERROR - Process-1 process died!
```

system log:
```
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: Process VM Poller:
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: Traceback (most recent call last):
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: self.run()
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: self._target(*self._args, **self._kwargs)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/opt/cloudscheduler/data_collectors/openstack/openstackPoller.py", line 238, in vm_poller
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: logging.error("unable to merge sessions, database incosistency or other error while proccessing vms for %s:%s:" % (cloud.group_name, cloud.cloud_name))
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: return self.impl.get(instance_state(instance), dict_)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 579, in get
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: value = state._load_expired(state, passive)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/state.py", line 592, in _load_expired
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: self.manager.deferred_scalar_loader(self, toload)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 713, in load_scalar_attributes
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: only_load_props=attribute_names)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/loading.py", line 223, in load_on_ident
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: return q.one()
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2814, in one
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: ret = self.one_or_none()
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2784, in one_or_none
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: ret = list(self)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: return self._execute_and_instances(context)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2876, in _execute_and_instances
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: close_with_result=True)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2885, in _get_bind_args
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: **kw
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/query.py", line 2867, in _connection_from_session
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: conn = self.session.connection(**kw)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 998, in connection
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: execution_options=execution_options)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 1003, in _connection_for_bind
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: engine, execution_options)
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 382, in _connection_for_bind
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: self._assert_active()
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/site-packages/sqlalchemy/orm/session.py", line 276, in _assert_active
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: % self._rollback_exception
May 31 17:18:21 csv2.heprc.uvic.ca python[1145121]: InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(
May 31 17:18:28 csv2.heprc.uvic.ca python[1145121]: Traceback (most recent call last):
May 31 17:18:28 csv2.heprc.uvic.ca python[1145121]: File "/opt/cloudscheduler/data_collectors/openstack/openstackPoller.py", line 788, in <module>
May 31 17:18:28 csv2.heprc.uvic.ca python[1145121]: process.start()
May 31 17:18:28 csv2.heprc.uvic.ca python[1145121]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 120, in start
May 31 17:18:28 csv2.heprc.uvic.ca python[1145121]: assert self._popen is None, 'cannot start a process twice'
May 31 17:18:28 csv2.heprc.uvic.ca python[1145121]: AssertionError: cannot start a process twice
```

My best guess is that we hit some sort of error after attempting to merge sessions and the cause of that error was a sqlalchemy object that is accessed to log the error in the exception handling block which then threw another exception which was not handled crashing the process.

Since I'm unsure what caused the initial exception as the program crashed before being able to log the error I've changed the order of the logging so that if it crashes again it will first log the initial exception before trying to report the group and cloud that the error occured with. Once the initial exception has been identified the handling can be updated or the management of the sqlalchemy objects can be improved as it seems to have occured during the merge.

**Comment by colsond** [comment]
This bug should also have been fixed as a result of restructuring database use. The openstack poller should now reliably keep the list of vms updated.
