### ISSUE TITLE
need to provide network for e.g. otter-a

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#76]
VM on otter won't start, because they have a choice of two networks:
```
Sep 27 10:36:28 csv2 csv2: DEBUG:urllib3.connectionpool:https://otter.heprc.uvic.ca:18774 "POST /v2.1/servers HTTP/1.1" 409 123
Sep 27 10:36:28 csv2 csv2: DEBUG:novaclient.v2.client:RESP: [409] Openstack-Api-Version: compute 2.1 X-Openstack-Nova-Api-Version: 2.1 Vary: OpenStack-API-Version, X-OpenStack-Nova-API-Version Content-Type: application/json; ch
arset=UTF-8 Content-Length: 123 X-Openstack-Request-Id: req-1027f7d5-e00c-4b4d-9c94-02f7b7773425 X-Compute-Request-Id: req-1027f7d5-e00c-4b4d-9c94-02f7b7773425 Date: Thu, 27 Sep 2018 17:36:28 GMT
Sep 27 10:36:28 csv2 csv2: RESP BODY: {"conflictingRequest": {"message": "Multiple possible networks found, use a Network ID to be more specific.", "code": 409}}
Sep 27 10:36:28 csv2 csv2: DEBUG:novaclient.v2.client:POST call to compute for https://otter.heprc.uvic.ca:18774/v2.1/servers used request id req-1027f7d5-e00c-4b4d-9c94-02f7b7773425
Sep 27 10:36:28 csv2 csv2: ERROR:cloudscheduler.openstackcloud:Multiple possible networks found, use a Network ID to be more specific. (HTTP 409) (Request-ID: req-1027f7d5-e00c-4b4d-9c94-02f7b7773425)
Sep 27 10:36:28 csv2 csv2: Traceback (most recent call last):
Sep 27 10:36:28 csv2 csv2: File "/opt/cloudscheduler/cloudscheduler/openstackcloud.py", line 166, in vm_create
Sep 27 10:36:28 csv2 csv2: security_groups=None, max_count=num)
Sep 27 10:36:28 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 1403, in create
Sep 27 10:36:28 csv2 csv2: **boot_kwargs)
Sep 27 10:36:28 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/v2/servers.py", line 802, in _boot
Sep 27 10:36:28 csv2 csv2: return_raw=return_raw, **kwargs)
Sep 27 10:36:28 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/base.py", line 361, in _create
Sep 27 10:36:28 csv2 csv2: resp, body = self.api.client.post(url, body=body)
Sep 27 10:36:28 csv2 csv2: File "/usr/lib/python3.6/site-packages/keystoneauth1/adapter.py", line 310, in post
Sep 27 10:36:28 csv2 csv2: return self.request(url, 'POST', **kwargs)
Sep 27 10:36:28 csv2 csv2: File "/usr/lib/python3.6/site-packages/novaclient/client.py", line 83, in request
Sep 27 10:36:28 csv2 csv2: raise exceptions.from_response(resp, body, url, method)
Sep 27 10:36:28 csv2 csv2: novaclient.exceptions.Conflict: Multiple possible networks found, use a Network ID to be more specific. (HTTP 409) (Request-ID: req-1027f7d5-e00c-4b4d-9c94-02f7b7773425)
Sep 27 10:36:28 csv2 csv2: DEBUG:cloudscheduler.openstackcloud:vm create
Sep 27 10:36:28 csv2 csv2: DEBUG:__main__:done booting on cloud otter-a
Sep 27 10:36:28 csv2 csv2: DEBUG:__main__:Seem to have booted enough for this job for now.
```

**Comment by crlb** [comment]
Database, views, UI, and unit tests completed (see 712676b9b4f40355513cb04d431775f93b0a2130, 62e66df434daf123df5d9d7d55486a98236f2ce8, 30e67cacb65fe9ebb08e94f83d109cd29c1873db, bc6de0cf397fb99080a3effeaa20fb2adc294cce, de6a871b5b2fa256d25313847a2a76dba8575a21). Waiting for scheduler changes.

**Comment by rseuster** [comment]
assigning now to Kevin. The web_view doesn't show the network in the Settings for clouds in csv2 yet.

**Comment by colsond** [comment]
nice work
