### ISSUE TITLE
mysql errors when retiring all VMs

### ISSUE THREAD

**Issue by rseuster** [hep-gc/cloudscheduler#84]
retiring all VMs in csv2 lead me to this error:
```
2018-10-17 09:46:45,054 - Command Poller - INFO - Retiring machine slot1@atlas--chameleon-a--177127179489188-1.novalocal
2018-10-17 09:46:45,712 - Command Poller - INFO - Retiring machine slot1@atlas--chameleon-a--177127179489188-2.novalocal
2018-10-17 09:46:46,365 - Command Poller - INFO - Retiring machine slot1@atlas--chameleon-a--177448565960962.novalocal
2018-10-17 09:46:46,403 - Machine Poller - ERROR - Failed to merge machine entry, aborting cycle...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1205, 'Lock wait timeout exceeded; try restarting transaction')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/cloudscheduler/data_collectors/condor/csmachines.py", line 131, in machine_poller
    db_session.merge(new_resource)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1839, in merge
    self._autoflush()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1407, in _autoflush
    util.raise_from_cause(e)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 1397, in _autoflush
    self.flush()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2177, in flush
    self._flush(objects)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2297, in _flush
    transaction.rollback(_capture_exception=True)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/session.py", line 2261, in _flush
    flush_context.execute()
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 177, in save_obj
    mapper, table, update)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 737, in _emit_update_statements
    execute(statement, multiparams)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib64/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 250, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 50, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 247, in execute
    res = self._query(query)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 411, in _query
    rowcount = self._do_query(q)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 374, in _do_query
    db.query(q)
  File "/usr/lib64/python3.6/site-packages/MySQLdb/connections.py", line 277, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.OperationalError) (1205, 'Lock wait timeout exceeded; t
ry restarting transaction') [SQL: 'UPDATE condor_machines SET my_current_time=%s WHERE condor_machines.name = %s'] [parameters: (1539794746, 'slot1@atlas--cc-east-a--2004361051750.novalocal')]
2018-10-17 09:46:46,407 - Machine Poller - ERROR - (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (_mysql_exceptions.OperationalError) (1205, 'Lock wait t
imeout exceeded; try restarting transaction') [SQL: 'UPDATE condor_machines SET my_current_time=%s WHERE condor_machines.name = %s'] [parameters: (1539794746, 'slot1@atlas--cc-east-a--2004361051750.novalocal')]
2018-10-17 09:46:47,027 - Command Poller - INFO - Retiring machine slot1@atlas--chameleon-a--212917709172520.novalocal
2018-10-17 09:46:47,709 - Command Poller - INFO - Retiring machine slot1@atlas--chameleon-a--219718457042314-4.novalocal
```
on the bright side, csv2 did retire all VMs in the end.

**Comment by colsond** [comment]
On Dev the way database connections are handled has been restructured, but I don't think the new method would avoid such an error  either.
What is happening here is the command poller is trying to update every entry that its running commands for but while its doing that it is maintaining a lock on the table so the other process (machine poller) has to wait for it. In this case it spent almost a minute performing operations before getting to a commit and thus timed out.

I think the solution is to batch commit updates, say every 50 or so merges, as this error didn't occur till over 100 merges, this should buy us enough time to beat the timeout even if mariadb or condor is busy.

**Comment by colsond** [comment]
fixed
