### ISSUE TITLE
cli bug

### ISSUE THREAD

**Issue by MarcusEbert** [hep-gc/cloudscheduler#86]
steps done:
git clone cloudscheduler  from master
cli/bin/cloudscheduler   (or cli/bin/cloudscheduler -H)

result:
mebert@heplw65:~/Git/cloudscheduler$ cli/bin/cloudscheduler -H
Traceback (most recent call last):
  File "cli/bin/cloudscheduler", line 7, in <module>
    from csv2_common import requests
  File "/hepuser/mebert/Git/cloudscheduler/cli/bin/csv2_common.py", line 141
    _form_data = {**form_data, **{'csrfmiddlewaretoken': gvar['csrf']}}
                   ^
SyntaxError: invalid syntax

expected result:
shows usage of the cli

**Comment by MarcusEbert** [comment]
After pull from master to get latest changes, no change with the error:
```
mebert@heplw65:~/Git/cloudscheduler$ ./cli/bin/cloudscheduler -h
Traceback (most recent call last):
  Fimebert@heplw65:~/Git/cloudscheduler$ ./cli/bin/cloudscheduler -h
Traceback (most recent call last):
  File "./cli/bin/cloudscheduler", line 7, in <module>
    from csv2_common import requests
  File "/hepuser/mebert/Git/cloudscheduler/cli/bin/csv2_common.py", line 141
    _form_data = {**form_data, **{'csrfmiddlewaretoken': gvar['csrf']}}
                   ^
SyntaxError: invalid syntax
mebert@heplw65:~/Git/cloudscheduler$ git status
# On branch master
nothing to commit, working directory clean
mebert@heplw65:~/Git/cloudscheduler$ git diff
mebert@heplw65:~/Git/cloudscheduler$le "./cli/bin/cloudscheduler", line 7, in <module>
    from csv2_common import requests
  File "/hepuser/mebert/Git/cloudscheduler/cli/bin/csv2_common.py", line 141
    _form_data = {**form_data, **{'csrfmiddlewaretoken': gvar['csrf']}}
                   ^
SyntaxError: invalid syntax
mebert@heplw65:~/Git/cloudscheduler$ git status
# On branch master
nothing to commit, working directory clean
mebert@heplw65:~/Git/cloudscheduler$ git diff
mebert@heplw65:~/Git/cloudscheduler$ git pull
Already up-to-date.
mebert@heplw65:~/Git/cloudscheduler$ 
```

**Comment by MarcusEbert** [comment]
Solution on CentOS7:
---------------------------
- yum install python36 python36-devel
- ln -sf /bin/python36 /bin/python3
- python36 -m pip install PyYAML
- python36 -m pip install requests

Since python3.5 pip is built-in and no external pip should be used.
